- src/main/java/com/yegor256/asto/Storage.java
@yegor256 , review the PR pleases.
> extend Storage with list method

- pom.xml
- src/main/java/com/yegor256/asto/Storage.java
- src/test/java/com/yegor256/asto/StorageTest.java
Use RxJava 3 for `Storage` interface rectification.
> Storage rectification

- pom.xml
#1 - updated versions plugin to `2.7`
> Updated versions plugin

- .github/workflows/git.yaml
- .rultor.yml
#9 - fixed rultor config (removed unnecessary commands).
Trigger required checks on `pull_request` events.
> Fixed rultor config

- .rultor.yml
#1 - configured  java home for rultor
> rultor java home

- pom.xml
#1 - fixed maven release config
> Maven release config

- pom.xml
#1 - fixed javadoc plugin (using 8 sources)
> Fixed javadoc plugin

- src/main/java/com/artipie/asto/BlockingStorage.java
> Add blocking wrapper over asto

- src/main/java/com/artipie/asto/ByteArray.java
> expose ByteArray to public

- src/main/java/com/artipie/asto/RxStorage.java
> Reactive wrapper for Storage

- src/main/java/com/artipie/asto/Key.java
#25 - added default decorator for key to use it for https://github.com/artipie/docker-adapter/pull/35
> Default decorator for key

- pom.xml
- src/main/java/com/artipie/asto/fs/FileStorage.java
> Fix FileStorage#save logging issues

- src/main/java/com/artipie/asto/Key.java
Added protective copying of key parts to Key.From constructor.
> Fixed safe copying in Key.From constructor

- README.md
- src/main/java/com/artipie/asto/Remaining.java
- src/main/java/com/artipie/asto/Storage.java
- src/main/java/com/artipie/asto/blocking/BlockingStorage.java
- src/main/java/com/artipie/asto/fs/FileStorage.java
- src/main/java/com/artipie/asto/fs/FileSystemTransaction.java
- src/main/java/com/artipie/asto/fs/RxFile.java
- src/main/java/com/artipie/asto/rx/RxStorage.java
- src/main/java/com/artipie/asto/rx/RxStorageWrapper.java
- src/main/java/com/artipie/asto/rx/RxTransactionWrapper.java
- src/test/java/com/artipie/asto/FileStorageTest.java
- src/test/java/com/artipie/asto/RxFileTest.java
Performance-wise a flow of Byte is worse than a Flow of ByteBuffer
Closes #41
> Replace Flow of Byte with Flow of ByteBuffer

- .github/workflows/maven.yml
- pom.xml
- src/test/java/com/artipie/asto/FileStorageTest.java
- src/test/java/com/artipie/asto/KeyTest.java
- src/test/java/com/artipie/asto/RemainingTest.java
- src/test/java/com/artipie/asto/RxFileTest.java
#53 - updated junit framework versin to 5.x and parent pom
> Updated junit and parent pom

- src/main/java/com/artipie/asto/Remaining.java
- src/test/java/com/artipie/asto/RemainingTest.java
#47 - added optional flag to restore buffer position in `Remaining` class
> Don't restore buffer position by default

- pom.xml
- src/main/java/com/artipie/asto/fs/RxFile.java
- src/test/java/com/artipie/asto/RxFileTest.java
closes #45 
* RxFile#save test enhanced with more iterations
* Fix RxFile#save implementation
* Stream errors are propagated to the resulted completable
> Fix RxFile#save and enhance RxFileTest#saveWorks with more iterations

- pom.xml
- src/main/java/com/artipie/asto/memory/InMemoryStorage.java
- src/main/java/com/artipie/asto/memory/package-info.java
- src/test/java/com/artipie/asto/InMemoryStorageTest.java
Issue #59 
Added InMemoryStorage class with only save() and value() methods implemented
> #59 - Added InMemoryStorage with only save() and value() methods

- src/main/java/com/artipie/asto/fs/FileStorage.java
- src/test/java/com/artipie/asto/FileStorageTest.java
* Vert.x instance is not created per each read/write opertaion
* @TempDir removed from Windows
related to #57
> Fix windows builds

- src/main/java/com/artipie/asto/fs/FileStorage.java
- src/test/java/com/artipie/asto/FileStorageTest.java
Closes issue #64 
Adds check if file by path is directory and tests for exists() method
> #64 - FileStorage.exists() changed to return false for directories

- src/main/java/com/artipie/asto/fs/RxFile.java
- src/test/java/com/artipie/asto/FileStorageTest.java
- src/test/java/com/artipie/asto/RxFileTest.java
* Close underlying AsyncFile after read stream completion
> Fix file descriptor issues with RxFile#flow

- src/main/java/com/artipie/asto/Key.java
- src/test/java/com/artipie/asto/KeyTest.java
Closes issue #69
Implements all improvements proposed in the issue.
> #69 - Improvements to Key class

- pom.xml
- src/main/java/com/artipie/asto/Key.java
- src/main/java/com/artipie/asto/Storage.java
- src/main/java/com/artipie/asto/fs/FileStorage.java
- src/main/java/com/artipie/asto/fs/FileSystemTransaction.java
- src/main/java/com/artipie/asto/memory/InMemoryStorage.java
- src/main/java/com/artipie/asto/rx/RxStorageWrapper.java
- src/main/java/com/artipie/asto/rx/RxTransactionWrapper.java
- src/test/java/com/artipie/asto/FileStorageTest.java
- src/test/java/com/artipie/asto/InMemoryStorageTest.java
> Migration from Java 9 from to Reactive streams

- src/main/java/com/artipie/asto/memory/InMemoryStorage.java
- src/test/java/com/artipie/asto/InMemoryStorageTest.java
Part of #59 
Added move() method and tests for it
> #59 - Added implementation for InMemoryStorage.move()

- .github/workflows/maven.yml
#82 - 1.8, 11 and 13 JDK matrix build
> JDK matrix build

- src/main/java/com/artipie/asto/memory/InMemoryStorage.java
- src/test/java/com/artipie/asto/InMemoryStorageExistsTest.java
- src/test/java/com/artipie/asto/InMemoryStorageTest.java
Part of #59
Added exists() method and tests for it
> #59 - Added implementation for InMemoryStorage.exists()

- src/main/java/com/artipie/asto/memory/InMemoryStorage.java
- src/test/java/com/artipie/asto/InMemoryStorageListTest.java
- src/test/java/com/artipie/asto/InMemoryStorageTest.java
Part of #59
Added list() method and tests for it
> #59 - Added implementation for InMemoryStorage.list()

- src/main/java/com/artipie/asto/Key.java
- src/test/java/com/artipie/asto/KeyTest.java
Currently, parts are not split against delimiter. This pull request fixes it.
> Split parts by delim

- src/main/java/com/artipie/asto/Key.java
- src/test/java/com/artipie/asto/KeyTest.java
#94 - added root key to get rid of workarounds like empty strings for root keys
> Added root key

- src/main/java/com/artipie/asto/fs/RxFile.java
Calling `.toList().blockingGet()`is something we want to avoid in a non-test  env.
> improve RxFile#save

- src/main/java/com/artipie/asto/s3/S3Storage.java
- src/test/java/com/artipie/asto/S3StorageTest.java
Part of #87 
Added S3Storage.exists() method implementation
> #87 - Added S3Storage.exists() method implementation

- src/main/java/com/artipie/asto/s3/S3Storage.java
- src/test/java/com/artipie/asto/S3StorageTest.java
Part of issue #87 
Added implementation for Storage.value() method in S3 storage.
> #87 - Added S3Storage.value() method implementation

- src/main/java/com/artipie/asto/s3/S3Storage.java
- src/test/java/com/artipie/asto/S3StorageTest.java
Part of #87 
Added S3Storage.list() method implementation
> #87 - Added S3Storage.list() method implementation

- src/main/java/com/artipie/asto/s3/S3Storage.java
- src/test/java/com/artipie/asto/S3StorageTest.java
Part of #87 
Added S3Storage.move() method implementation
> #87 - Added S3Storage.move() method implementation

- src/main/java/com/artipie/asto/s3/Bucket.java
- src/main/java/com/artipie/asto/s3/MultipartUpload.java
- src/main/java/com/artipie/asto/s3/S3Storage.java
- src/test/java/com/artipie/asto/s3/BucketTest.java
- src/test/java/com/artipie/asto/s3/package-info.java
Closes issue #96
Solves complexity in MultipartUpload by extracting Bucket class as new layer of abstraction over S3Client
> #96 - Extracted Bucket from MultipartUpload

- src/test/java/com/artipie/asto/FileStorageTest.java
- src/test/java/com/artipie/asto/StorageExtension.java
> #113 - Using generic storage tests for FileStorage

- src/main/java/com/artipie/asto/fs/FileStorage.java
> fix FileStorage:list with Key.ROOT issue

- pom.xml
- src/main/java/com/artipie/asto/google/GoogleStorage.java
- src/main/java/com/artipie/asto/google/package-info.java
- src/main/java/com/artipie/asto/rx/RxStorageWrapper.java
> Placeholders for #119 (Google Storage)

- src/main/java/com/artipie/asto/s3/S3Storage.java
Part of #87
Upload small content using put request in S3Storage even if size is unknown. Storage tries to read content up to some 10Mb, if content is bigger then multipart upload is used
> #87 - Upload small content using put request when size is unknown

- pom.xml
- src/main/java/com/artipie/asto/google/GoogleStorage.java
> value for GS

- src/main/java/com/artipie/asto/Key.java
> Key ctor should take List as parameter, not Collection

- src/main/java/com/artipie/asto/fs/FileStorage.java
- src/main/java/com/artipie/asto/fs/RxFile.java
- src/test/java/com/artipie/asto/FileStorageTest.java
#142 - added a test to save and load big enough 1 GB file, discovered performance issue (this file is saved about few minutes), and fixed performance issue in `RxFile`.
> Fixed performance issue in filestorage

- src/main/java/com/artipie/asto/Storage.java
Closes #144 
Added Storage.Wrap - abstract decorator for Storage
> #144 - Added Storage.Wrap a forwarding decorator for Storage interface

- src/main/java/com/artipie/asto/Storage.java
- src/main/java/com/artipie/asto/blocking/BlockingStorage.java
- src/main/java/com/artipie/asto/fs/FileStorage.java
- src/main/java/com/artipie/asto/fs/FileSystemTransaction.java
- src/main/java/com/artipie/asto/google/GoogleStorage.java
- src/main/java/com/artipie/asto/memory/InMemoryStorage.java
- src/main/java/com/artipie/asto/memory/InMemoryTransaction.java
- src/main/java/com/artipie/asto/rx/RxStorage.java
- src/main/java/com/artipie/asto/rx/RxStorageWrapper.java
- src/main/java/com/artipie/asto/rx/RxTransactionWrapper.java
- src/main/java/com/artipie/asto/s3/S3Storage.java
- src/test/java/com/artipie/asto/StorageSizeTest.java
Closes #146 
Added size() method for all Storage implementations and tests suit for this method.
> #146 - Added Storage.size() method

- pom.xml
- src/main/java/com/artipie/asto/fs/RxFile.java
> Bump vert.x version 3.8.5 -> 3.9.0

- src/main/java/com/artipie/asto/Copy.java
- src/main/java/com/artipie/asto/Sync.java
Related to #160. 
`Sync` class has been created with a puzzle to implement it.
> Add Sync class with a puzzle to implement it

- src/main/java/com/artipie/asto/rx/RxCopy.java
This Pull Request provides an implementation for RxCopy class
Can be merged after #164
> Implement RxCopy

- src/main/java/com/artipie/asto/rx/RxCopy.java
- src/test/java/com/artipie/asto/CopyTest.java
Add a test for Copy class.
Can be merged after #165
> A test for Copy

- src/main/java/com/artipie/asto/Key.java
- src/main/java/com/artipie/asto/fs/FileStorage.java
This change would address a number of logging issues when #string method is not called.
> Add toString for Key

- .github/workflows/codecov.yml
- .github/workflows/maven.yml
- .github/workflows/pdd.yml
- .github/workflows/xcop.yml
- README.md
- pom.xml
> Enabled jacoco reports

- .github/workflows/deploy-snapshot.yml
- .github/workflows/maven.yml
- pom.xml
#178 - deploy snapshots to Artipie central
> Deploy snapshots

- src/main/java/com/artipie/asto/Key.java
- src/main/java/com/artipie/asto/SubStorage.java
#139 - implemented sub storage with prefixed keys
> Implemented sub storage

- src/main/java/com/artipie/asto/LoggingStorage.java
- src/test/java/com/artipie/asto/LoggingStorageTest.java
> #182 - Logging storage added

- src/main/java/com/artipie/asto/s3/S3Storage.java
Closes #193 
Multipart flag added to S3Storage
> #193 - Added multipart upload feature flag to S3Storage

- src/main/java/com/artipie/asto/s3/S3Storage.java
Closes #197 
Calculating size of Content when value is saved is S3Storage with disabled multipart
> #197 - Calculating size of Content in S3Storage.save when multipart disabled

- src/main/java/com/artipie/asto/Concatenation.java
- src/test/java/com/artipie/asto/ConcatenationTest.java
For #191
Previous approach: create new Buffer for every new loaded chunk. New buffer size = previous buffer size + chunk size
New approach: keep the same Buffer between loads. When Buffer capacity is overflowed, new Buffer is created with capacity twice large as original
> fix Concatenation performance issue

- pom.xml
- src/main/java/com/artipie/asto/OneTimeConsumablePublisher.java
- src/main/java/com/artipie/asto/OneTimePublisher.java
- src/test/java/com/artipie/asto/OneTimePublisherTest.java
- src/test/java/com/artipie/asto/OneTimePublisherVerificationTest.java
> Implement one-time publisher

- src/main/java/com/artipie/asto/Content.java
- src/main/java/com/artipie/asto/OneTimePublisher.java
- src/main/java/com/artipie/asto/blocking/BlockingStorage.java
- src/main/java/com/artipie/asto/fs/FileStorage.java
- src/main/java/com/artipie/asto/memory/InMemoryStorage.java
- src/main/java/com/artipie/asto/s3/S3Storage.java
- src/test/java/com/artipie/asto/ConcatenationTest.java
- src/test/java/com/artipie/asto/FileStorageTest.java
- src/test/java/com/artipie/asto/StorageSaveAndLoadTest.java
- src/test/java/com/artipie/asto/ext/ContentDigestTest.java
- src/test/java/com/artipie/asto/memory/InMemoryStorageTest.java
- src/test/java/com/artipie/asto/s3/S3StorageTest.java
Every storage implementation has been updated in accordance with #206 puzzle.
_Closes #206
> Use one time publisher

- src/main/java/com/artipie/asto/ext/KeyLastPart.java
- src/test/java/com/artipie/asto/ext/KeyLastPartTest.java
To close #215 I've added class to obtain last part of the key.
> #215 - KeyLastPart introduced

- src/main/java/com/artipie/asto/test/TestResource.java
- src/main/java/com/artipie/asto/test/package-info.java
- src/test/java/com/artipie/asto/test/TestResourceTest.java
- src/test/java/com/artipie/asto/test/package-info.java
- src/test/resources/test.txt
Introduced `TestResource` and test for it to close #218.
> #218 - introduced TestResource

- src/main/java/com/artipie/asto/ext/ContentDigest.java
- src/main/java/com/artipie/asto/ext/Digests.java
- src/test/java/com/artipie/asto/ext/DigestsTest.java
Closes #221: 
- added sha-512 enum item
- extracted enum to separate file
- added class to obtain enum item from string
- added tests
> #221 - support sha-512 digest algorithm

- src/main/java/com/artipie/asto/lock/Lock.java
- src/main/java/com/artipie/asto/lock/StorageLock.java
- src/main/java/com/artipie/asto/lock/package-info.java
- src/test/java/com/artipie/asto/lock/StorageLockTest.java
- src/test/java/com/artipie/asto/lock/package-info.java
Part of #214 
Added `Lock` interface and `StorageLock` implementation with acquiring implemented.
> #214 - Added Lock and StorageLock with acquiring

- src/main/java/com/artipie/asto/Content.java
- src/main/java/com/artipie/asto/lock/StorageLock.java
- src/test/java/com/artipie/asto/ContentTest.java
- src/test/java/com/artipie/asto/lock/StorageLockTest.java
Closes #227 
Added empty Content and it's usage
> #227 - Added empty Content and it's usage

- src/main/java/com/artipie/asto/lock/storage/Proposals.java
- src/main/java/com/artipie/asto/lock/storage/StorageLock.java
- src/main/java/com/artipie/asto/lock/storage/package-info.java
- src/test/java/com/artipie/asto/lock/storage/StorageLockTest.java
- src/test/java/com/artipie/asto/lock/storage/package-info.java
For #231
Moved `StorageLock` to `com.artipie.asto.lock.storage` and extracted `Proposals`.
> #231 - Moved `StorageLock` to `com.artipie.asto.lock.storage` and extracted `Proposals`

- src/main/java/com/artipie/asto/AsyncContent.java
- src/main/java/com/artipie/asto/cache/Cache.java
- src/main/java/com/artipie/asto/cache/CacheControl.java
- src/main/java/com/artipie/asto/cache/DigestVerification.java
- src/main/java/com/artipie/asto/cache/StorageCache.java
- src/test/java/com/artipie/asto/cache/CacheControlTest.java
- src/test/java/com/artipie/asto/cache/DigestVerificationTest.java
- src/test/java/com/artipie/asto/cache/StorageCacheTest.java
#233 - verify cache by message digest
> Digest cache verification

- src/main/java/com/artipie/asto/fs/FileStorage.java
- src/test/java/com/artipie/asto/FileStorageTest.java
- src/test/java/com/artipie/asto/StorageSaveAndLoadTest.java
Closes #217 
Add size to the constructor of `FileStorage`.
> #217 - Fix size of the content

- src/main/java/com/artipie/asto/lock/RxLock.java
> #246 - Added RxLock

- src/main/java/com/artipie/asto/SubStorage.java
- src/main/java/com/artipie/asto/UnderLockOperation.java
- src/main/java/com/artipie/asto/fs/FileStorage.java
- src/main/java/com/artipie/asto/memory/InMemoryStorage.java
- src/main/java/com/artipie/asto/s3/S3Storage.java
- src/test/java/com/artipie/asto/StorageExclusivelyTest.java
Part of #237 
Storages exclusively method implementation using `UnderLockOperation`
> #237 - Storages exclusively method implementation

- src/main/java/com/artipie/asto/lock/storage/Proposals.java
- src/test/java/com/artipie/asto/lock/storage/StorageLockTest.java
Closes #260 
Handle concurrently deleted proposals in `StorageLock`
> #260 - Handle concurrently deleted proposals in StorageLock

- src/main/java/com/artipie/asto/blocking/BlockingStorage.java
> Revert signature changes made with BlockingStorage

- src/test/java/com/artipie/asto/StorageSaveAndLoadTest.java
> Atomicity check

- src/main/java/com/artipie/asto/FailedCompletionStage.java
- src/main/java/com/artipie/asto/UnderLockOperation.java
- src/main/java/com/artipie/asto/lock/storage/StorageLock.java
- src/main/java/com/artipie/asto/s3/S3Storage.java
- src/test/java/com/artipie/asto/lock/RetryLockTest.java
Closes #287 
Added `FailedCompletionStage` and it's usage
> #287 - Added FailedCompletionStage and it's usage

- src/main/java/com/artipie/asto/ext/ContentAs.java
- src/test/java/com/artipie/asto/ext/ContentAsTest.java
Closes #293 
I've moved `ContentAs` from artipie and added test for this class
> #293 - moved ContentAs class

- src/main/java/com/artipie/asto/ext/ContentAs.java
Made ctor in `ContentAs` public
> Public ctor in ContentAs

- src/main/java/com/artipie/asto/Copy.java
- src/main/java/com/artipie/asto/rx/RxCopy.java
- src/test/java/com/artipie/asto/CopyTest.java
> #296 - Copy all keys

- pom.xml
- src/main/java/com/artipie/asto/fs/FileStorage.java
- src/test/java/com/artipie/asto/FileStorageTest.java
Closes #302 
Delete empty directories along with files.
> #302 - delete empty directories

- pom.xml
- src/main/java/com/artipie/asto/fs/FileStorage.java
- src/main/java/com/artipie/asto/fs/RxFile.java
Closes #251 - bump rio dep from v0.2.1 to v0.3
with improved performance of big file write operations.
> Bump rio v0.3

- pom.xml
- src/main/java/com/artipie/asto/misc/Scalar.java
- src/main/java/com/artipie/asto/misc/UncheckedIOScalar.java
- src/main/java/com/artipie/asto/misc/UncheckedScalar.java
- src/test/java/com/artipie/asto/misc/UncheckedScalarTest.java
Closes #323 
Added unchecked scalars `UncheckedScalar` and `UncheckedIOScalar` and test.
> Added unchecked scalars and test

- pom.xml
Part of #325
Updated vertx, checked all deps (see issue descr) and excluded jackson-databind from main code.
> Updated vertx, excluded jackson-databind

- src/main/java/com/artipie/asto/Copy.java
- src/test/java/com/artipie/asto/CopyTest.java
Added new construbtor for `Copy` class to copy
storage using `Predicate<? super Key>` instead of fixed set
of keys. Added test.
Issue: #327
Closes: #327
> feature: copy storage with predicate

- pom.xml
Declared VertX, S3 and Etcd storage provides as provided dependencies
Issue: artipie/artipie#926
> deps: declare optional dependencies as provided

- CHANGELOG.md
> Updated changelog for 1.4.0

- src/main/java/com/artipie/asto/streams/StorageValuePipeline.java
- src/test/java/com/artipie/asto/streams/StorageValuePipelineTest.java
Part of #333 
Extended `StorageValuePipeline` to accept diff keys: one key is to read from and another is to write processing result to.
This is needed in rpm to read metadata from repository location and save the result to temp location for further processing.
> Extended `StorageValuePipeline` to accept diff keys

- CHANGELOG.md
Added changelog for v1.9.0 release
> Added changelog for v1.9.0 release

- src/test/java/com/artipie/asto/SubStorageTest.java
Closes #354
- Test methods `size`, `move` and `save`
- Add a puzzle to continue to add more tests
> test: Adds some tests for SubStorage

- pom.xml
- src/main/java/com/artipie/asto/LoggingStorage.java
- src/test/java/com/artipie/asto/LoggingStorageTest.java
Closes #345
Test logging on methods `save`, `exists` and `list`
> test: Tests logging on some LoggingStorage's operations

- src/test/java/com/artipie/asto/LoggingStorageTest.java
Closes #370
For `LoggingStorage` :
- Refactor some tests
- Test other methods
> test: test that all LoggingStorage methods are logged properly

- src/test/java/com/artipie/asto/SubStorageTest.java
Add tests for `SubStorage` metadata and delete methods.
Close: #369
> test: add more tests for SubStorage

- CHANGELOG.md
> Added changelog for 1.10.0

- src/main/java/com/artipie/asto/Key.java
- src/main/java/com/artipie/asto/SubStorage.java
- src/main/java/com/artipie/asto/etcd/EtcdStorage.java
- src/test/java/com/artipie/asto/StorageExtension.java
- src/test/java/com/artipie/asto/etcd/EtcdStorageITCase.java
Closes #310
- Setup etcd cluster for `StorageExtension`
- Fix some tests
- Disable `EtcdStorage` tests for `Windows` in `StorageExtension` tests
> test: setup etcd cluster for StorageExtension

- src/main/java/com/artipie/asto/rx/RxStorageWrapper.java
- src/test/java/com/artipie/asto/blocking/BlockingStorageTest.java
- src/test/java/com/artipie/asto/rx/RxStorageWrapperTest.java
- src/test/java/com/artipie/asto/rx/package-info.java
Test remaining functions of `BlockingStorage` and all functions of `RxStorageWrapper`
Close: #55
Ref: #383
> test: cover BlockingStorage and RxStorageWrapper

- src/main/java/com/artipie/asto/s3/S3Storage.java
> fix: do not use deprecated methods in S3Storage

- src/main/java/com/artipie/asto/streams/StorageValuePipeline.java
Closes: #430
- `StorageValuePipeline` implemented using `ByteArrayInputStream`/`ByteArrayOutputStream` streams
> fix: `StorageValuePipeline` implemented without reactive IO

- README.md
Part of https://github.com/artipie/artipie/issues/1031 
Corrected and extended readme.
> fix: extended README.md

- README.md
Part of https://github.com/artipie/artipie/issues/1031
Removed not actual link and corrected grammar mistake.
> fix: readme corrections

- CHANGELOG.md
- README.md
Closes: #449
- changes readme file
- added v1.13.0 to changelog
> docs: change dependency description in the readme file

- asto-core/src/main/java/com/artipie/asto/SubStorage.java
closes: #181 
- removed non-actual puzzle
> Remove non-actual puzzle

- asto-core/src/main/java/com/artipie/asto/test/StorageWhiteboxVerification.java
- asto-redis/src/main/java/com/artipie/asto/redis/RedisStorage.java
- asto-redis/src/test/java/com/artipie/asto/redis/RedisStorageWhiteboxVerificationTest.java
part of #445 
- fixed an error in verification tests
- added `RedisStorage` verification tests
> RedisStorage verification tests

- asto-core/src/main/java/com/artipie/asto/Key.java
- asto-core/src/main/java/com/artipie/asto/fs/FileStorage.java
- asto-core/src/test/java/com/artipie/asto/SubStorageTest.java
- asto-vertx-file/src/main/java/com/artipie/asto/fs/VertxFileStorage.java
- asto-vertx-file/src/test/java/com/artipie/asto/VertxFileStorageVerificationTest.java
part of #445
Fixed VertxFileStorage verification tests for case root sub storage
> fix `VertxFileStorage` verification tests for case root sub storage

- asto-core/src/main/java/com/artipie/asto/factory/FactoryLoader.java
- asto-core/src/main/java/com/artipie/asto/factory/StoragesLoader.java
part of #487 
sorry, I've forget to make abstract methods public so they can be overridden in http...
> fix: make FactoryLoader.java methods public

- asto-core/src/main/java/com/artipie/asto/misc/Cleanable.java
> feat: `Cleanable` interface
