artipie/asto

.rultor.yml
#1 - removed deprecated JDK option `MaxPermSize`
> Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
`mx1g` also not needed here, since Java heap size will set to the maximum available memory on the running machine. This options usually used to reduce the size of available memory.
=> Removed deprecated options

.rultor.yml
Rultor has broken `$HOME/.m2/settings.xml`, using `../settings.xml` explicitly.
=> Fixed rultor release commands

src/main/java/com/artipie/asto/blocking/BlockingStorage.java, src/test/java/com/artipie/asto/FileStorageTest.java
fixes #31 
`BlockingStorage#save` now works via ReactiveStorageWrapper, which handes `CompletableFuture<Void>` to `Completable` conversion correctly.
=> Fix + add a test for blocking version of storage

src/test/java/com/artipie/asto/RemainingTest.java
#43 - mark and reset `ByteBuffer` before and after reading from it
=> Fixed remaining bytebuffer wrapper

src/main/java/com/artipie/asto/Storage.java, src/main/java/com/artipie/asto/blocking/BlockingStorage.java, src/main/java/com/artipie/asto/fs/FileStorage.java, src/main/java/com/artipie/asto/fs/FileSystemTransaction.java, src/main/java/com/artipie/asto/fs/RxFile.java, src/main/java/com/artipie/asto/rx/RxStorage.java, src/main/java/com/artipie/asto/rx/RxStorageWrapper.java, src/main/java/com/artipie/asto/rx/RxTransactionWrapper.java, src/test/java/com/artipie/asto/FileStorageTest.java
This pull requests adds move feature to ASTO storage, e.g. atomic operation of moving content from one key to another that could be handled efficiently by storage implementation.
The feature is requested by adapter modules using ASTO storage, see https://github.com/artipie/nuget-adapter/issues/21
=> #51 - Added Storage.move() method

src/main/java/com/artipie/asto/Storage.java, src/main/java/com/artipie/asto/blocking/BlockingStorage.java, src/main/java/com/artipie/asto/fs/FileStorage.java, src/main/java/com/artipie/asto/fs/FileSystemTransaction.java, src/main/java/com/artipie/asto/rx/RxStorage.java, src/main/java/com/artipie/asto/rx/RxStorageWrapper.java, src/main/java/com/artipie/asto/rx/RxTransactionWrapper.java, src/test/java/com/artipie/asto/FileStorageTest.java
Issue: #62 
This PR modifies Storage interface, FileStorage implementation and related classes such as BlockingStorage, RxStorage etc
=> #62 - Storage.list() method accepts Key as prefix

pom.xml, src/main/java/com/artipie/asto/fs/RxFile.java
Closes issue #78 
Removed dependency on Vert.x snapshot, changed RxFile.save() method to be blocking and non-reactive
=> #78 - Vert.x downgrade

.rultor.yml
#82 - using jdk8 docker image to release jars
=> Using jdk8 to build release binary

src/main/java/com/artipie/asto/fs/RxFile.java, src/test/java/com/artipie/asto/RxFileTest.java
#91 - discovered the bug in `RxFile` when overwriting existing file with longer string: the file won't be truncated in this case.
=> Reproduced and fixed rxfile

src/main/java/com/artipie/asto/Key.java, src/test/java/com/artipie/asto/KeyTest.java
Closes issue #94 
Added check for part being empty to Key.From.string() method.
=> #94 - Key.From does not allow empty parts

src/main/java/com/artipie/asto/fs/FileStorage.java, src/main/java/com/artipie/asto/fs/RxFile.java, src/test/java/com/artipie/asto/RxFileTest.java
In general, it is a bad idea to use this constructor in production code, because it creates 2xCPU amount of threads.
=> Remove RxFile(Path) constructor

src/main/java/com/artipie/asto/s3/MultipartUpload.java, src/main/java/com/artipie/asto/s3/S3Storage.java, src/test/java/com/artipie/asto/S3StorageTest.java
Part of issue #87 
Aborting multipart upload if it failed to be uploaded. Otherwise failed multipart uploads are leaking and wasting space in S3
=> #87 - Aborting multipart upload if failed to upload content

src/main/java/com/artipie/asto/Storage.java, src/main/java/com/artipie/asto/blocking/BlockingStorage.java, src/main/java/com/artipie/asto/fs/FileStorage.java, src/main/java/com/artipie/asto/fs/FileSystemTransaction.java, src/main/java/com/artipie/asto/fs/RxFile.java, src/main/java/com/artipie/asto/memory/InMemoryStorage.java, src/main/java/com/artipie/asto/memory/InMemoryTransaction.java, src/main/java/com/artipie/asto/rx/RxStorage.java, src/main/java/com/artipie/asto/rx/RxStorageWrapper.java, src/main/java/com/artipie/asto/rx/RxTransactionWrapper.java, src/main/java/com/artipie/asto/s3/S3Storage.java, src/test/java/com/artipie/asto/FileStorageTest.java, src/test/java/com/artipie/asto/S3StorageTest.java, src/test/java/com/artipie/asto/StorageDeleteTest.java
Closes issue #110 
Added `delete()` method to `Storage` with implementations for file, S3 and in memory storage.
Also added `delete()` method to `BlockingStorage` and `RxStorage`
=> #110 - Added Storage.delete() method

src/test/java/com/artipie/asto/S3StorageTest.java, src/test/java/com/artipie/asto/StorageSaveAndLoadTest.java
Part of issue #87
Removed duplication of bucket creating code in S3Storage
S3StorageTest.shouldFailToSaveMultipartUploadWhenFailedToReadContent() generalized and moved to StorageSaveAndLoadTest.shouldFailToSaveErrorContent()
shouldNotExistForUnknownObject() removed as duplicate of StorageExistsTest.shouldNotExistForUnknownKey()
=> #87 - S3StorageTest refactoring

src/main/java/com/artipie/asto/s3/MultipartUpload.java, src/main/java/com/artipie/asto/s3/S3Storage.java, src/test/java/com/artipie/asto/S3StorageTest.java
Part of issue #87 
`S3Storage.save()` uses put request when content is small, so the operation is done only single call and so much more efficient
=> #96 - Uploading smaller content using put request in S3Storage

src/main/java/com/artipie/asto/Key.java
missed file for #131 
previous version still works (0.16.1) but just because of using Key.ROOT singleton in the code. Call with Key.From(Collections.emptyList()) will fails without this fix
=> fix FileStorage:list with Key.ROOT issue: add missed file

pom.xml, src/main/java/com/artipie/asto/fs/FileStorage.java, src/main/java/com/artipie/asto/memory/InMemoryStorage.java, src/test/java/com/artipie/asto/memory/InMemoryStorageTest.java, src/test/java/com/artipie/asto/memory/package-info.java
Closes #153 
Reason for example code to fail is endless `Publisher`. It is getting read inside `synchronized`, so read operation cannot obtain the lock.
Fixed it by  bringing content reading outside of synchronized section + got rid of other Single.blockingGet() usage because it creates errors in Vert.x environment
=> #153 - Removed Single.blockingGet() calls

src/main/java/com/artipie/asto/Copy.java, src/main/java/com/artipie/asto/rx/RxCopy.java
Add a reactive version of `Copy`, which will serve as an implementation for `Copy`
=> Implement Copy via RxCopy

src/main/java/com/artipie/asto/s3/S3Storage.java, src/test/java/com/artipie/asto/S3StorageTest.java, src/test/java/com/artipie/asto/s3/S3StorageTest.java
Part of #163 
Added tests to illustrate the problem and adds caching for content being saved by `S3Storage`.
This is not ideal solution and it is needed to change code so it won't cache all content, but only data up to `MIN_MULTIPART` size in bytes.
=> #163 - S3 storage saves value without reading it twice

src/main/java/com/artipie/asto/fs/FileStorage.java
That is how the log message looks now:
```
[INFO] vert.x-eventloop-thread-3 com.artipie.asto.fs.FileStorage: Found 2 objects by the prefix "com.artipie.asto.Key$From@66f262b" in temp-gem-index by temp-gem-index/quick: []
```
the actual prefix name should be in the log
=> Fix ls logging

src/main/java/com/artipie/asto/fs/RxFile.java, src/main/java/com/artipie/asto/rx/RxStorageWrapper.java, src/main/java/com/artipie/asto/rx/RxTransactionWrapper.java
All the methods returning Rx primitives made properly lazy: using Rx `defer` to start execution only after `subscribe` call.
Closes #189
=> Proper laziness in Rx components

src/main/java/com/artipie/asto/fs/FileStorage.java, src/test/java/com/artipie/asto/FileStorageTest.java, src/test/java/com/artipie/asto/StorageSaveAndLoadTest.java
Closes #203 
Atomic `FileStorage.save` writes data to temporary file first, then moves it to end destination
=> #203 - Atomic save in FileStorage

src/main/java/com/artipie/asto/fs/FileStorage.java, src/test/java/com/artipie/asto/StorageSaveAndLoadTest.java
Closes #204 
* A test which ensures that the returned content is always consumable only once has been created
* FileStorage was fixed so the test passes
=> Test that value returned content is always consumable only once

src/main/java/com/artipie/asto/lock/StorageLock.java, src/test/java/com/artipie/asto/lock/StorageLockTest.java
Part of #214 
Added `release` implementation to `StorageLock`. Auto release of lock when `acquire` has failed.
=> #214 - Release implemented in StorageLock

pom.xml, src/main/java/com/artipie/asto/cache/Cache.java, src/main/java/com/artipie/asto/cache/CacheControl.java, src/main/java/com/artipie/asto/cache/StorageCache.java, src/main/java/com/artipie/asto/cache/package-info.java, src/main/java/com/artipie/asto/test/ContentIs.java, src/test/java/com/artipie/asto/cache/StorageCacheTest.java, src/test/java/com/artipie/asto/cache/package-info.java
#225 - initial storage cache implementation:
- created primitive `StorageCache` implementation to improve it later (reads from remote to storage and returns storage after that)
- created basic interfaces `Cache` and `CacheControl`
- unit tests for `StorageCache`
=> Initial storage cache implementation

pom.xml, src/main/java/com/artipie/asto/lock/RetryLock.java, src/test/java/com/artipie/asto/lock/RetryLockTest.java
Closes #214 
Added `RetryLock` that allows to make multiple acquire attempts on faulty origin lock
=> #214 - Added RetryLock

src/main/java/com/artipie/asto/lock/storage/Proposals.java, src/main/java/com/artipie/asto/lock/storage/StorageLock.java, src/test/java/com/artipie/asto/lock/storage/StorageLockTest.java
Part of #231 
Writing expiration time as value in proposal in `StorageLock` so it can be read and evaluated by other processes which is to be implemented later.
=> #231 - Added expiration time to lock, writing the value in proposal

src/main/java/com/artipie/asto/lock/storage/Proposals.java, src/test/java/com/artipie/asto/lock/storage/StorageLockTest.java
Closes #231 
Using expiration time when acquiring `StorageLock`. Acquiring fails only if not expired proposals exists.
=> #231 - Using expiration time when acquiring StorageLock

src/main/java/com/artipie/asto/UnderLockOperation.java, src/test/java/com/artipie/asto/StorageExclusivelyTest.java
Closes #237
Proper handling of errors in `Storage.exclusively` implementations
=> #237 - Proper handling of errors in Storage.exclusively implementations

src/main/java/com/artipie/asto/ValueNotFoundException.java, src/main/java/com/artipie/asto/fs/FileStorage.java, src/main/java/com/artipie/asto/memory/InMemoryStorage.java, src/main/java/com/artipie/asto/s3/S3Storage.java, src/test/java/com/artipie/asto/StorageSaveAndLoadTest.java, src/test/java/com/artipie/asto/StorageSizeTest.java
Part of #260
Throwing `ValueNotFoundException` when value absent in storage. This is required to distinguish this sort of errors from others on calls to `value` and `size` methods
=> #260 - Throwing ValueNotFoundException when value absent in storage

src/main/java/com/artipie/asto/AsyncContent.java, src/main/java/com/artipie/asto/cache/FromRemoteCache.java, src/main/java/com/artipie/asto/cache/FromStorageCache.java, src/test/java/com/artipie/asto/cache/FromRemoteCacheTest.java, src/test/java/com/artipie/asto/cache/FromStorageCacheTest.java
Closes #284 
Added implementation of `Cache` to always load content from remote and add to storage and get from cache only if remote failed to return content.
=> #284 - cache impl to load from remote

src/main/java/com/artipie/asto/cache/Cache.java, src/main/java/com/artipie/asto/cache/FromRemoteCache.java, src/main/java/com/artipie/asto/cache/FromStorageCache.java, src/main/java/com/artipie/asto/cache/Remote.java, src/test/java/com/artipie/asto/cache/FromRemoteCacheTest.java, src/test/java/com/artipie/asto/cache/FromStorageCacheTest.java, src/test/java/com/artipie/asto/cache/RemoteWithErrorHandlingTest.java
Part of #286 
Changed `Cache` signature to use `Remote`, corrected implementations and added `Remote.Failed`.
=> #286 - changed Cache to use Remote

src/main/java/com/artipie/asto/SubStorage.java, src/main/java/com/artipie/asto/ext/CompletableFutureSupport.java, src/main/java/com/artipie/asto/fs/FileStorage.java, src/main/java/com/artipie/asto/fs/VertxFileStorage.java, src/main/java/com/artipie/asto/memory/InMemoryStorage.java, src/test/java/com/artipie/asto/StorageSaveAndLoadTest.java
Closes #201 - added check for `ROOT` key in `save` and `value` storage
methods:
- added tests to find all problem methods in `StorageSaveAndLoadTest`
- fixed all `Storage` implementation to fail on `ROOT` key
=> Check ROOT key for save and load

src/test/java/com/artipie/asto/cache/FromStorageCacheTest.java
Per #299:
- Prevent dead lock
- Replace `CountDownLatch` with `Semaphore`
=> #299: Prevent dead lock in tests

.0pdd.yml, README.md, pom.xml, src/main/java/com/artipie/asto/etcd/EtcdStorage.java, src/main/java/com/artipie/asto/etcd/package-info.java, src/test/java/com/artipie/asto/etcd/EtcdStorageITCase.java, src/test/java/com/artipie/asto/etcd/package-info.java
For #305 - introduced etcd storage, added integration test
using junit extension.
=> Added etcd storage

src/main/java/com/artipie/asto/fs/FileStorage.java
Closes #307 
Corrected `FileStorage#deleteEmptyParts()` not to throw `NoSuchFileException` if empty folder we are going to remove does not exist.
=> Do not throw `NoSuchFileException` while removing empty dirs in `FileStorage`

src/main/java/com/artipie/ArtipieException.java, src/main/java/com/artipie/asto/ArtipieIOException.java, src/main/java/com/artipie/asto/Key.java, src/main/java/com/artipie/asto/OneTimePublisher.java, src/main/java/com/artipie/asto/SubStorage.java, src/main/java/com/artipie/asto/ValueNotFoundException.java, src/main/java/com/artipie/asto/cache/FromRemoteCache.java, src/main/java/com/artipie/asto/etcd/EtcdStorage.java, src/main/java/com/artipie/asto/fs/FileStorage.java, src/main/java/com/artipie/asto/fs/RxFile.java, src/main/java/com/artipie/asto/fs/VertxFileStorage.java, src/main/java/com/artipie/asto/lock/storage/Proposals.java, src/main/java/com/artipie/asto/memory/InMemoryStorage.java, src/main/java/com/artipie/asto/s3/EstimatedContentCompliment.java, src/main/java/com/artipie/asto/s3/InternalExceptionHandle.java, src/main/java/com/artipie/asto/s3/S3Storage.java, src/main/java/com/artipie/package-info.java, src/test/java/com/artipie/asto/OneTimePublisherTest.java, src/test/java/com/artipie/asto/StorageExclusivelyTest.java, src/test/java/com/artipie/asto/StorageSaveAndLoadTest.java, src/test/java/com/artipie/asto/lock/storage/StorageLockTest.java, src/test/java/com/artipie/asto/s3/InternalExceptionHandleTest.java
Fixes #311 - added `ArtipieException` base class and
`ArtipieIOException` for `asto` module, replaced
all API-related exceptions in storage implementations and
supplementary classes with these exceptions. Updated tests
to expect correct exception types on failure.
=> Added artipie base exception classes

src/main/java/com/artipie/asto/misc/UncheckedConsumer.java, src/main/java/com/artipie/asto/misc/UncheckedFunc.java, src/main/java/com/artipie/asto/misc/UncheckedIOConsumer.java, src/main/java/com/artipie/asto/misc/UncheckedIOFunc.java, src/main/java/com/artipie/asto/misc/package-info.java, src/test/java/com/artipie/asto/misc/UncheckedConsumerTest.java, src/test/java/com/artipie/asto/misc/UncheckedFuncTest.java, src/test/java/com/artipie/asto/misc/package-info.java
Closes #317 
Moved `UncheckedConsumer` and `UncheckedFunc` from rpm and corrected them to throw `ArtipieException`, also added specific `UncheckedIOConsumer` and `UncheckedIOFunc`  for IO errors.
=> Added consumers and functions with `ArtipieException`

src/main/java/com/artipie/asto/memory/BenchmarkStorage.java, src/test/java/com/artipie/asto/memory/BenchmarkStorageDeleteTest.java, src/test/java/com/artipie/asto/memory/BenchmarkStorageExistsTest.java, src/test/java/com/artipie/asto/memory/BenchmarkStorageTest.java
Part of #314
Added implementation of `delete` and  `exists` for benchmark storage and tests. 
For `delete` operation `synchronized` block was used because it is necessary firstly to check existence and after that add to set in case of absence
=> Add implementation for `delete` and `exists`

README.md, src/main/java/com/artipie/asto/Key.java, src/main/java/com/artipie/asto/memory/BenchmarkStorage.java, src/test/java/com/artipie/asto/KeyTest.java, src/test/java/com/artipie/asto/memory/BenchmarkStorageDeleteTest.java, src/test/java/com/artipie/asto/memory/BenchmarkStorageExistsTest.java, src/test/java/com/artipie/asto/memory/BenchmarkStorageListTest.java, src/test/java/com/artipie/asto/memory/BenchmarkStorageSizeTest.java
Part of #314
Added implementation of `list` and `size` for benchmark storage and tests.
Optimize `delete` by avoid using synchronize block because the result of `add` operation could be used instead
=> Add implementation for `list` and `size`, optimize `delete`

src/main/java/com/artipie/asto/memory/BenchmarkStorage.java, src/test/java/com/artipie/asto/StorageExtension.java, src/test/java/com/artipie/asto/memory/BenchmarkStorageMoveTest.java
Closes #314 
Added implementation of `move` and `exclusively`. 
Included `BenchmarkStorage` to `StorageExtension` to enable pool of tests which should be passed by all implementations of storage
=> Add implementation of `move` and `exclusively`

pom.xml
=> Exclude `com.google.android:annotations` from etcd dep

CHANGELOG.md, pom.xml
=> Exclude fasterxml jackson databind from `vertx-rx-java2`

CHANGELOG.md, src/main/java/com/artipie/asto/streams/StorageValuePipeline.java
Part of #333 
Fixed method `StorageValuePipeline.process()` to be public
=> Make method `StorageValuePipeline.process()` public

src/main/java/com/artipie/asto/test/TestResource.java, src/test/java/com/artipie/asto/test/TestResourceTest.java
Added method for `TestResource` to save it directly to
file (`Path`).
Ticket: #218
Related: artipie/gem-adapter#130
=> feat: test resource save to file

src/main/java/com/artipie/asto/SubStorage.java, src/test/java/com/artipie/asto/SubStorageTest.java
Closes #351 
Fixed problem with `list` operation of `SubStorage`, added some tests, todo for other tests.
The problem is described in the original issue:
> I found two problems with SubStorage:
> 1) Complete lack of tests
> 2) `list` operation does work correctly in some cases: when `SubStorage` is created with `Ket.ROOT` as prefix, list removes first met `/` symbol, thus returning not existing items. For example, if the sub storage contains `abc/xyz/hello.txt`, then list by `abc` key will return `abcxyz/hello.txt`
> 
The first problem is fixed by adding some tests (complete set of tests will be added later, by the `todo`), the second problem is fixed by correcting the regexp, used in `list` method.
=> Fixed and tested `SubStorage`

src/main/java/com/artipie/asto/LoggingStorage.java, src/main/java/com/artipie/asto/Meta.java, src/main/java/com/artipie/asto/Storage.java, src/main/java/com/artipie/asto/SubStorage.java, src/main/java/com/artipie/asto/blocking/BlockingStorage.java, src/main/java/com/artipie/asto/etcd/EtcdStorage.java, src/main/java/com/artipie/asto/fs/FileMeta.java, src/main/java/com/artipie/asto/fs/FileStorage.java, src/main/java/com/artipie/asto/fs/VertxFileStorage.java, src/main/java/com/artipie/asto/memory/BenchmarkStorage.java, src/main/java/com/artipie/asto/memory/InMemoryStorage.java, src/main/java/com/artipie/asto/rx/RxStorageWrapper.java, src/main/java/com/artipie/asto/s3/S3HeadMeta.java, src/main/java/com/artipie/asto/s3/S3Storage.java, src/test/java/com/artipie/asto/FileStorageTest.java, src/test/java/com/artipie/asto/LoggingStorageTest.java, src/test/java/com/artipie/asto/StorageSaveAndLoadTest.java, src/test/java/com/artipie/asto/StorageSizeTest.java, src/test/java/com/artipie/asto/etcd/EtcdStorageITCase.java, src/test/java/com/artipie/asto/fs/FileMetaTest.java, src/test/java/com/artipie/asto/fs/package-info.java, src/test/java/com/artipie/asto/lock/storage/StorageLockTest.java, src/test/java/com/artipie/asto/memory/BenchmarkStorageSizeTest.java, src/test/java/com/artipie/asto/s3/S3HeadMetaTest.java, src/test/java/com/artipie/asto/s3/S3StorageTest.java
Added `Meta` interface to represent blob metadata,
updated storage with new method `metadata(Key)`,
deprecated `size(Key)` method since it's covered by metadata method.
Added interfaces `Meta.ReadOperator<T>` and `Meta.WriteOperator<T>`
to serialize and parse data values to intermediate `Map<String, String>`
container. Updated all `Storage`s implementation and related tests.
**Reasons behind this implementation:** each storage can provide different
metadata, e.g. storage based on file-system `FileStorage` can provide
timestampts for file creation time, update time and access time;
S3 storage can provide MD5 hash of content without loading it from
remote bucket, etc. So we need some dynamic and extendable metadata
representation, `Map<String, String>` could be good for this. Another …
=> feat(metadata): storage metadata API

src/main/java/com/artipie/asto/fs/FileStorage.java, src/test/java/com/artipie/asto/StorageExtension.java, src/test/java/com/artipie/asto/StorageListTest.java
Closes #371 
The problem is described in #371, but what is actually wrong is to call equals on keys like
`Key.ROOT.equals(anotherKey)` 
as in the case with `SubStorage` `anotherKey` is an instance of `SubStorage.PrefixedKey`, not `Key.From` and `equals()` (this is the `equals()` overridden in Key.From` class) will return false.
I've fixed it by comparing keys by their string representations, added various `SubStorage`'s to `StorageExtension` and test with `Key.ROOT` to `StorageListTest`.
=> Compare keys by string representation

src/main/java/com/artipie/asto/fs/FileStorage.java, src/test/java/com/artipie/asto/FileStorageTest.java
Closes #332
Throw an exception when attempting to write out of `FileStorage` scope
=> fix: prevent file to be written out of FileStorage scope

pom.xml, src/main/java/com/artipie/asto/fs/FileStorage.java
Refactor key path validation to use futures.
Check read key path before performing content reading.
Ref: #332
=> fix(fs): check path for FS read

src/main/java/com/artipie/asto/Storage.java, src/test/java/com/artipie/asto/StorageExtension.java, src/test/java/com/artipie/asto/StorageWrapped.java
We missed to add method `metadata` in `Storage.Wrap`. Here, we fix it.
Fix: #392
=> fix(storage): add metadata method to standard decorator

src/main/java/com/artipie/asto/MetaCommon.java, src/test/java/com/artipie/asto/MetaCommonTest.java
We implemented `size` method to start.
Close: #393
=> feat: introduce helper for Meta's standard methods

pom.xml, src/main/java/com/artipie/asto/ArtipieStorage.java, src/test/java/com/artipie/asto/ArtipieStorageTest.java
Closes #405 
- implemented `Storage` as `ArtipieStorage` for artipie/files-adapter via HTTP
- added tests for `ArtipieStorage`
=> feat: Storage for artipie/files-adapter via HTTP

pom.xml, src/main/java/com/artipie/asto/LoggingStorage.java, src/test/java/com/artipie/asto/LoggingStorageTest.java
`jcabi-log:0.20.1` does not support recent versions of logging libraries.
So, we replaced it by `java.util.logging`.
Close: #413
=> test: fix tests for `LoggingStorage`

src/test/java/com/artipie/asto/s3/BucketTest.java, src/test/java/com/artipie/asto/s3/S3StorageTest.java
Close: #414 
`CompleteMultipartUploadRequest` should contain a list of uploaded parts, otherwise an exception will be thrown.
=> fix: fixed BucketTest#shouldUploadPartAndCompleteMultipartUpload test

src/main/java/com/artipie/asto/Splitting.java, src/main/java/com/artipie/asto/s3/MultipartUpload.java, src/test/java/com/artipie/asto/SplittingTest.java, src/test/java/com/artipie/asto/s3/S3StorageTest.java
closes: #421
- created `Splitting` class to split `ByteBuffer` at parts
- created tests to check `Splitting` implementation
- added filling of `multipartUpload` field of `CompleteMultipartUploadRequest`
=> fix: added parts information to `CompleteMultipartUploadRequest`

src/main/java/com/artipie/asto/streams/StorageValuePipeline.java, src/test/java/com/artipie/asto/streams/StorageValuePipelineTest.java
Close: #427
- implemented asynchronous starting of read, action and write futures inside the `StorageValuePipeline#processWithResult` method.
- added test to check `StorageValuePipeline` in the case when value is getting by key "from" has large size.
=> fix: StorageValuePipeline#processWithResult hanging

asto-core/src/main/java/com/artipie/asto/fs/FileStorage.java, asto-core/src/main/java/com/artipie/asto/test/StorageWhiteboxVerification.java, asto-core/src/test/java/com/artipie/asto/FileStorageWhiteboxVerificationTest.java, asto-etcd/src/test/java/com/artipie/asto/etcd/EtcdStorageVerificationTest.java, asto-redis/src/test/java/com/artipie/asto/redis/RedisStorageWhiteboxVerificationTest.java, asto-s3/src/test/java/com/artipie/asto/S3StorageWhiteboxVerificationTest.java, asto-vertx-file/src/main/java/com/artipie/asto/fs/VertxFileStorage.java, asto-vertx-file/src/test/java/com/artipie/asto/VertxFileStorageVerificationTest.java
Whitebox Verification base test should use junit jupiter `Test` annotation to actually run the tests for various storages and I've fixed error in `FileStorage.list()` method (we could not have missed it if Verification test was actually working).
=> fix: verification base tests corrected and file storage fixed
